package com.litongjava.spider.rmp.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRumiRmpRating<M extends BaseRumiRmpRating<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setTeacherId(java.lang.Long teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}
	
	public java.lang.Long getTeacherId() {
		return getLong("teacher_id");
	}
	
	public M setSchoolId(java.lang.Long schoolId) {
		set("school_id", schoolId);
		return (M)this;
	}
	
	public java.lang.Long getSchoolId() {
		return getLong("school_id");
	}
	
	public M setAdminReviewedAt(java.util.Date adminReviewedAt) {
		set("admin_reviewed_at", adminReviewedAt);
		return (M)this;
	}
	
	public java.util.Date getAdminReviewedAt() {
		return getDate("admin_reviewed_at");
	}
	
	public M setAttendanceMandatory(java.lang.String attendanceMandatory) {
		set("attendance_mandatory", attendanceMandatory);
		return (M)this;
	}
	
	public java.lang.String getAttendanceMandatory() {
		return getStr("attendance_mandatory");
	}
	
	public M setClarityRatingRounded(java.lang.Integer clarityRatingRounded) {
		set("clarity_rating_rounded", clarityRatingRounded);
		return (M)this;
	}
	
	public java.lang.Integer getClarityRatingRounded() {
		return getInt("clarity_rating_rounded");
	}
	
	public M setClassName(java.lang.String className) {
		set("class_name", className);
		return (M)this;
	}
	
	public java.lang.String getClassName() {
		return getStr("class_name");
	}
	
	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}
	
	public M setCourseType(java.lang.Integer courseType) {
		set("course_type", courseType);
		return (M)this;
	}
	
	public java.lang.Integer getCourseType() {
		return getInt("course_type");
	}
	
	public M setCreatedByUser(java.lang.Boolean createdByUser) {
		set("created_by_user", createdByUser);
		return (M)this;
	}
	
	public java.lang.Boolean getCreatedByUser() {
		return getBoolean("created_by_user");
	}
	
	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return getDate("date");
	}
	
	public M setDifficultyRatingRounded(java.lang.Integer difficultyRatingRounded) {
		set("difficulty_rating_rounded", difficultyRatingRounded);
		return (M)this;
	}
	
	public java.lang.Integer getDifficultyRatingRounded() {
		return getInt("difficulty_rating_rounded");
	}
	
	public M setFlagStatus(java.lang.String flagStatus) {
		set("flag_status", flagStatus);
		return (M)this;
	}
	
	public java.lang.String getFlagStatus() {
		return getStr("flag_status");
	}
	
	public M setGrade(java.lang.String grade) {
		set("grade", grade);
		return (M)this;
	}
	
	public java.lang.String getGrade() {
		return getStr("grade");
	}
	
	public M setHelpfulRatingRounded(java.lang.Integer helpfulRatingRounded) {
		set("helpful_rating_rounded", helpfulRatingRounded);
		return (M)this;
	}
	
	public java.lang.Integer getHelpfulRatingRounded() {
		return getInt("helpful_rating_rounded");
	}
	
	public M setWouldLikeTakeAgain(java.lang.Integer wouldLikeTakeAgain) {
		set("would_like_take_again", wouldLikeTakeAgain);
		return (M)this;
	}
	
	public java.lang.Integer getWouldLikeTakeAgain() {
		return getInt("would_like_take_again");
	}
	
	public M setIsForCredit(java.lang.Boolean isForCredit) {
		set("is_for_credit", isForCredit);
		return (M)this;
	}
	
	public java.lang.Boolean getIsForCredit() {
		return getBoolean("is_for_credit");
	}
	
	public M setIsForOnlineClass(java.lang.Boolean isForOnlineClass) {
		set("is_for_online_class", isForOnlineClass);
		return (M)this;
	}
	
	public java.lang.Boolean getIsForOnlineClass() {
		return getBoolean("is_for_online_class");
	}
	
	public M setMaskCount(java.lang.Integer maskCount) {
		set("mask_count", maskCount);
		return (M)this;
	}
	
	public java.lang.Integer getMaskCount() {
		return getInt("mask_count");
	}
	
	public M setQualityRating(java.lang.Integer qualityRating) {
		set("quality_rating", qualityRating);
		return (M)this;
	}
	
	public java.lang.Integer getQualityRating() {
		return getInt("quality_rating");
	}
	
	public M setRatingTags(java.lang.String ratingTags) {
		set("rating_tags", ratingTags);
		return (M)this;
	}
	
	public java.lang.String getRatingTags() {
		return getStr("rating_tags");
	}
	
	public M setTextbookIsUsed(java.lang.Boolean textbookIsUsed) {
		set("textbook_is_used", textbookIsUsed);
		return (M)this;
	}
	
	public java.lang.Boolean getTextbookIsUsed() {
		return getBoolean("textbook_is_used");
	}
	
	public M setThumbsDownTotal(java.lang.Integer thumbsDownTotal) {
		set("thumbs_down_total", thumbsDownTotal);
		return (M)this;
	}
	
	public java.lang.Integer getThumbsDownTotal() {
		return getInt("thumbs_down_total");
	}
	
	public M setThumbsUpTotal(java.lang.Integer thumbsUpTotal) {
		set("thumbs_up_total", thumbsUpTotal);
		return (M)this;
	}
	
	public java.lang.Integer getThumbsUpTotal() {
		return getInt("thumbs_up_total");
	}
	
	public M setSourceUrl(java.lang.String sourceUrl) {
		set("source_url", sourceUrl);
		return (M)this;
	}
	
	public java.lang.String getSourceUrl() {
		return getStr("source_url");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

