package com.litongjava.spider.rmp.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysHttpRequestResponseStatistics<M extends BaseSysHttpRequestResponseStatistics<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setRequestIp(java.lang.String requestIp) {
		set("request_ip", requestIp);
		return (M)this;
	}
	
	public java.lang.String getRequestIp() {
		return getStr("request_ip");
	}
	
	public M setRequestUri(java.lang.String requestUri) {
		set("request_uri", requestUri);
		return (M)this;
	}
	
	public java.lang.String getRequestUri() {
		return getStr("request_uri");
	}
	
	public M setRequestHeader(java.lang.String requestHeader) {
		set("request_header", requestHeader);
		return (M)this;
	}
	
	public java.lang.String getRequestHeader() {
		return getStr("request_header");
	}
	
	public M setRequestContentType(java.lang.String requestContentType) {
		set("request_content_type", requestContentType);
		return (M)this;
	}
	
	public java.lang.String getRequestContentType() {
		return getStr("request_content_type");
	}
	
	public M setRequestBody(java.lang.String requestBody) {
		set("request_body", requestBody);
		return (M)this;
	}
	
	public java.lang.String getRequestBody() {
		return getStr("request_body");
	}
	
	public M setResponseStatusCode(java.lang.Integer responseStatusCode) {
		set("response_status_code", responseStatusCode);
		return (M)this;
	}
	
	public java.lang.Integer getResponseStatusCode() {
		return getInt("response_status_code");
	}
	
	public M setResponseBody(java.lang.String responseBody) {
		set("response_body", responseBody);
		return (M)this;
	}
	
	public java.lang.String getResponseBody() {
		return getStr("response_body");
	}
	
	public M setElapsed(java.lang.Long elapsed) {
		set("elapsed", elapsed);
		return (M)this;
	}
	
	public java.lang.Long getElapsed() {
		return getLong("elapsed");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

