package com.litongjava.spider.rmp.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRumiRmpSchoolSummary<M extends BaseRumiRmpSchoolSummary<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setCampusCondition(java.lang.Double campusCondition) {
		set("campus_condition", campusCondition);
		return (M)this;
	}
	
	public java.lang.Double getCampusCondition() {
		return getDouble("campus_condition");
	}
	
	public M setCampusLocation(java.lang.Double campusLocation) {
		set("campus_location", campusLocation);
		return (M)this;
	}
	
	public java.lang.Double getCampusLocation() {
		return getDouble("campus_location");
	}
	
	public M setCareerOpportunities(java.lang.Double careerOpportunities) {
		set("career_opportunities", careerOpportunities);
		return (M)this;
	}
	
	public java.lang.Double getCareerOpportunities() {
		return getDouble("career_opportunities");
	}
	
	public M setClubAndEventActivities(java.lang.Double clubAndEventActivities) {
		set("club_and_event_activities", clubAndEventActivities);
		return (M)this;
	}
	
	public java.lang.Double getClubAndEventActivities() {
		return getDouble("club_and_event_activities");
	}
	
	public M setFoodQuality(java.lang.Double foodQuality) {
		set("food_quality", foodQuality);
		return (M)this;
	}
	
	public java.lang.Double getFoodQuality() {
		return getDouble("food_quality");
	}
	
	public M setInternetSpeed(java.lang.Double internetSpeed) {
		set("internet_speed", internetSpeed);
		return (M)this;
	}
	
	public java.lang.Double getInternetSpeed() {
		return getDouble("internet_speed");
	}
	
	public M setLibraryCondition(java.lang.Double libraryCondition) {
		set("library_condition", libraryCondition);
		return (M)this;
	}
	
	public java.lang.Double getLibraryCondition() {
		return getDouble("library_condition");
	}
	
	public M setSchoolReputation(java.lang.Double schoolReputation) {
		set("school_reputation", schoolReputation);
		return (M)this;
	}
	
	public java.lang.Double getSchoolReputation() {
		return getDouble("school_reputation");
	}
	
	public M setSchoolSafety(java.lang.Double schoolSafety) {
		set("school_safety", schoolSafety);
		return (M)this;
	}
	
	public java.lang.Double getSchoolSafety() {
		return getDouble("school_safety");
	}
	
	public M setSchoolSatisfaction(java.lang.Double schoolSatisfaction) {
		set("school_satisfaction", schoolSatisfaction);
		return (M)this;
	}
	
	public java.lang.Double getSchoolSatisfaction() {
		return getDouble("school_satisfaction");
	}
	
	public M setSocialActivities(java.lang.Double socialActivities) {
		set("social_activities", socialActivities);
		return (M)this;
	}
	
	public java.lang.Double getSocialActivities() {
		return getDouble("social_activities");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

