package com.litongjava.spider.rmp.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRumiRmpProfessorRatingThumb<M extends BaseRumiRmpProfessorRatingThumb<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setRatingId(java.lang.Long ratingId) {
		set("rating_id", ratingId);
		return (M)this;
	}
	
	public java.lang.Long getRatingId() {
		return getLong("rating_id");
	}
	
	public M setComputerId(java.lang.String computerId) {
		set("computer_id", computerId);
		return (M)this;
	}
	
	public java.lang.String getComputerId() {
		return getStr("computer_id");
	}
	
	public M setThumbsDown(java.lang.Integer thumbsDown) {
		set("thumbs_down", thumbsDown);
		return (M)this;
	}
	
	public java.lang.Integer getThumbsDown() {
		return getInt("thumbs_down");
	}
	
	public M setThumbsUp(java.lang.Integer thumbsUp) {
		set("thumbs_up", thumbsUp);
		return (M)this;
	}
	
	public java.lang.Integer getThumbsUp() {
		return getInt("thumbs_up");
	}
	
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}
	
	public M setTeacherId(java.lang.Long teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}
	
	public java.lang.Long getTeacherId() {
		return getLong("teacher_id");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

