package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseCourseChats;

/**
 * Generated by java-db.
 */
public class CourseChats extends BaseCourseChats<CourseChats> {
  private static final long serialVersionUID = 1L;
	public static final CourseChats dao = new CourseChats().dao();
	/**
	 * 
	 */
  public static final String tableName = "course_chats";
  public static final String primaryKey = "id";
  // private java.lang.Object id
  // private java.lang.String userId
  // private java.util.Date createdAt
  // private java.lang.String name
  // private java.lang.Boolean deleted
  // private java.lang.String usedDoc
  // private java.lang.String metadata
  // private java.lang.Long schoolId
  // private java.lang.Long appId
  // private java.lang.String type
  // private java.lang.Integer chatType

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

