package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpProfessorRatingThumb;

/**
 * Generated by java-db.
 */
public class RumiRmpProfessorRatingThumb extends BaseRumiRmpProfessorRatingThumb<RumiRmpProfessorRatingThumb> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpProfessorRatingThumb dao = new RumiRmpProfessorRatingThumb().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_professor_rating_thumb";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Long ratingId
  // private java.lang.String computerId
  // private java.lang.Integer thumbsDown
  // private java.lang.Integer thumbsUp
  // private java.lang.Integer userId
  // private java.lang.Long teacherId
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

