package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiEmbedding;

/**
 * Generated by java-db.
 */
public class RumiEmbedding extends BaseRumiEmbedding<RumiEmbedding> {
  private static final long serialVersionUID = 1L;
	public static final RumiEmbedding dao = new RumiEmbedding().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_embedding";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String t
  // private java.lang.String v
  // private java.lang.String m
  // private java.lang.String md5

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

