package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpSchoolSummary;

/**
 * Generated by java-db.
 */
public class RumiRmpSchoolSummary extends BaseRumiRmpSchoolSummary<RumiRmpSchoolSummary> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpSchoolSummary dao = new RumiRmpSchoolSummary().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_school_summary";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Double campusCondition
  // private java.lang.Double campusLocation
  // private java.lang.Double careerOpportunities
  // private java.lang.Double clubAndEventActivities
  // private java.lang.Double foodQuality
  // private java.lang.Double internetSpeed
  // private java.lang.Double libraryCondition
  // private java.lang.Double schoolReputation
  // private java.lang.Double schoolSafety
  // private java.lang.Double schoolSatisfaction
  // private java.lang.Double socialActivities
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

