package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpSchool;

/**
 * Generated by java-db.
 */
public class RumiRmpSchool extends BaseRumiRmpSchool<RumiRmpSchool> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpSchool dao = new RumiRmpSchool().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_school";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.math.BigDecimal avgRatingRounded
  // private java.lang.String city
  // private java.lang.String country
  // private java.lang.Integer legacyId
  // private java.lang.String name
  // private java.lang.Integer numRatings
  // private java.lang.String state
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

