package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpSchoolRatingThumb;

/**
 * Generated by java-db.
 */
public class RumiRmpSchoolRatingThumb extends BaseRumiRmpSchoolRatingThumb<RumiRmpSchoolRatingThumb> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpSchoolRatingThumb dao = new RumiRmpSchoolRatingThumb().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_school_rating_thumb";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Long campusRatingId
  // private java.lang.String computerId
  // private java.lang.Integer legacyId
  // private java.lang.Integer thumbsDown
  // private java.lang.Integer thumbsUp
  // private java.lang.Integer userId
  // private java.lang.Long schoolId
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

