package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpProfessor;

/**
 * Generated by java-db.
 */
public class RumiRmpProfessor extends BaseRumiRmpProfessor<RumiRmpProfessor> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpProfessor dao = new RumiRmpProfessor().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_professor";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String firstName
  // private java.lang.String lastName
  // private java.lang.String name
  // private java.lang.Long schoolId
  // private java.lang.String department
  // private java.lang.Long departmentId
  // private java.math.BigDecimal avgDifficultyRounded
  // private java.math.BigDecimal avgRatingRounded
  // private java.lang.Long mostUsefulRatingId
  // private java.lang.Integer numRatings
  // private java.lang.String sourceUrl
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId
  // private java.lang.String firstNameVector
  // private java.lang.String lastNameVector
  // private java.lang.String nameVector

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

