package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpProfessorRatingTag;

/**
 * Generated by java-db.
 */
public class RumiRmpProfessorRatingTag extends BaseRumiRmpProfessorRatingTag<RumiRmpProfessorRatingTag> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpProfessorRatingTag dao = new RumiRmpProfessorRatingTag().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_professor_rating_tag";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String tagName
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

