package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpSchoolDepartments;

/**
 * Generated by java-db.
 */
public class RumiRmpSchoolDepartments extends BaseRumiRmpSchoolDepartments<RumiRmpSchoolDepartments> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpSchoolDepartments dao = new RumiRmpSchoolDepartments().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_school_departments";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Integer dId
  // private java.lang.String name
  // private java.lang.Long schoolId
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

