package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiMessage;

/**
 * Generated by java-db.
 */
public class RumiMessage extends BaseRumiMessage<RumiMessage> {
  private static final long serialVersionUID = 1L;
	public static final RumiMessage dao = new RumiMessage().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_message";
  public static final String primaryKey = "uuid";
  // private java.lang.Object uuid
  // private java.util.Date createdAt
  // private java.util.Date updatedAt
  // private java.util.Date deletedAt
  // private java.lang.String sessionId
  // private java.lang.String role
  // private java.lang.String content
  // private java.lang.Object metadata
  // private java.lang.Boolean hiddenFromUser
  // private java.lang.Boolean liked

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

