package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiSchoolDict;

/**
 * Generated by java-db.
 */
public class RumiSchoolDict extends BaseRumiSchoolDict<RumiSchoolDict> {
  private static final long serialVersionUID = 1L;
	public static final RumiSchoolDict dao = new RumiSchoolDict().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_school_dict";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Integer rmpSchoolId
  // private java.lang.String fullName
  // private java.lang.String abbrName
  // private java.lang.String botName
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

