package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpProfessorRatingTagMapping;

/**
 * Generated by java-db.
 */
public class RumiRmpProfessorRatingTagMapping extends BaseRumiRmpProfessorRatingTagMapping<RumiRmpProfessorRatingTagMapping> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpProfessorRatingTagMapping dao = new RumiRmpProfessorRatingTagMapping().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_professor_rating_tag_mapping";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Long tagId
  // private java.lang.Integer tabCount
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

