package com.litongjava.spider.rmp.model;

import com.litongjava.spider.rmp.model.base.BaseRumiRmpSchoolRating;

/**
 * Generated by java-db.
 */
public class RumiRmpSchoolRating extends BaseRumiRmpSchoolRating<RumiRmpSchoolRating> {
  private static final long serialVersionUID = 1L;
	public static final RumiRmpSchoolRating dao = new RumiRmpSchoolRating().dao();
	/**
	 * 
	 */
  public static final String tableName = "rumi_rmp_school_rating";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Integer clubsRating
  // private java.lang.String comment
  // private java.lang.Boolean createdByUser
  // private java.util.Date date
  // private java.lang.String facilitiesRating
  // private java.lang.String flagStatus
  // private java.lang.Integer foodRating
  // private java.lang.Integer happinessRating
  // private java.lang.Integer internetRating
  // private java.lang.Integer legacyId
  // private java.lang.Integer locationRating
  // private java.lang.Integer opportunitiesRating
  // private java.lang.Integer reputationRating
  // private java.lang.Integer safetyRating
  // private java.lang.Integer socialRating
  // private java.lang.Integer thumbsDownTotal
  // private java.lang.Integer thumbsUpTotal
  // private java.lang.Long schoolId
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

